//
//  ZYSDKConstKey.h
//  ZYWebSDK
//
//  Created by admin on 2019/10/10.
//  Copyright © 2019 Octopus. All rights reserved.
//

#import <UIKit/UIKit.h>

UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKLOGIN;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKINIT;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKPAYSUCCESS;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKQUICKLYLOGIN;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKNORMALLOGIN;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKPHONELOGIN;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKPHONEREGIST;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKEMAILLOGIN;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKEMAILREGIST;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKLOGINSUCCESS;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKLOGINDISSVIEW;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONFACEBOOKLOGINSHOWVIEW;
UIKIT_EXTERN NSString *const ZYSDKNOTIFICATIONGOOGLELOGIN;
