# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZYWebSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZYWebSDKDemo
pod 'ZYWebOverseasSDK'
pod 'GoogleSignIn', '~> 4.4.0'
pod 'FBSDKLoginKit'
pod 'ZYWebSDKFBKit'
end
